### ISSUE TITLE
Despite having pykerberos installed, request-kerberos cannot 'import kerberos'

### ISSUE THREAD

**Issue by mdufrasne** [requests/requests-kerberos#101]
When the script fails to find kerberos, it tries to load winkerberos, assuming it is running on Windows. But in fact, I am on Linux and pykerberos is in fact installed -- I did some reading and it seems pykerberos is what should be used.

bash-3.2$ python example.2.py

Traceback (most recent call last):
  File "example.2.py", line 3, in <module>
    from requests_kerberos import HTTPKerberosAuth, OPTIONAL
  File "/home/woogie/.local/lib/python2.7/site-packages/requests_kerberos/__init__.py", line 17, in <module>
    from .kerberos_ import HTTPKerberosAuth, REQUIRED, OPTIONAL, DISABLED
  File "/home/woogie/.local/lib/python2.7/site-packages/requests_kerberos/kerberos_.py", line 4, in <module>
    **import winkerberos as kerberos
ImportError: No module named winkerberos**

bash-3.2$ pip list --format=columns
Package           Version
----------------- -----------
asn1crypto        0.22.0
certifi           2017.7.27.1
cffi              1.10.0
chardet           3.0.4
cryptography      2.0.3
enum34            1.1.6
idna              2.6
ipaddress         1.0.18
ndg-httpsclient   0.4.3
odata             0.2
pip               9.0.1
pyasn1            0.3.3
pycparser         2.18
pykerberos        1.1.14
pyOpenSSL         17.2.0
python-dateutil   2.6.1
requests          2.18.4
requests-kerberos 0.11.0
setuptools        36.3.0
six               1.10.0
urllib3           1.22
wheel             0.29.0

**Comment by mdufrasne** [comment]
I'm on python 2.7.13 by the way

**Comment by mdufrasne** [comment]
If I just try import kerberos, I actually get this error:
>>> import kerberos
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/mdufrasne/.local/lib/python2.7/site-packages/kerberos.so: undefined symbol: GSS_C_NT_USER_NAME

**Comment by mdufrasne** [comment]
Forgive this Python noob - when I encountered the error, I used pip - using python setup.py install made the error disappear.
