### ISSUE TITLE
Auth broken when using v0.13

### ISSUE THREAD

**Issue by NicolasT** [requests/requests-kerberos#167]
I have an application using `requests-kerberos`. When using version 0.12, authentication with a Kerberos service works fine. However, when upgrading to 0.13, things fail. It seems this is related to the change to `pyspnego`, indeed I could bisect `requests-kerberos` to

```
5dfe4b0cdfe5158d81f6644e07862087d4e6f007 is the first bad commit
commit 5dfe4b0cdfe5158d81f6644e07862087d4e6f007
Author: Jordan Borean <...>
Date:   Thu Oct 28 14:51:30 2021 +1000

    Change underlying lib to pyspnego
```

The application authenticates against a Keycloak SSO server (version 12.0.4) integrated with a standard CentOS Kerberos environment.

Some (slightly redacted) logging from `requests-kerberos` and `spnego`:

```
DEBUG:urllib3.connectionpool:https://... "GET /auth/realms/.../protocol/openid-connect/auth?response_type=code&client_id=...&redirect_uri=https%3A%2F%2F....invalid%2F&scope=openid+email+profile&state=...&response_mode=query&code_challenge=...&code_challenge_method=S256 HTTP/1.1" 401 610
DEBUG:requests_kerberos.kerberos_:handle_401(): Handling: 401
DEBUG:spnego._gss:GSSAPI does not support required the NTLM interfaces: Major (65536): An unsupported mechanism was requested, Minor (0): Unknown error
DEBUG:spnego._gss:GSSAPI step input: 
DEBUG:spnego._gss:GSSAPI step output: ...
DEBUG:requests_kerberos.kerberos_:authenticate_user(): Authorization header: Negotiate ...
DEBUG:urllib3.connectionpool:https://...:8443 "GET /auth/realms/.../protocol/openid-connect/auth?response_type=code&client_id=...&redirect_uri=https%3A%2F%2F....invalid%2F&scope=openid+email+profile&state=...&response_mode=query&code_challenge=...&code_challenge_method=S256 HTTP/1.1" 200 3816
```
Note the last request is an HTTP 200, whilst what's expected (and indeed, it is when using 0.12) is 302: it appears Keycloak simply renders a login page.

At the same time, Keycloak seems to have issues with the request and run into NPEs: when using 0.13, it logs
```
21:29:26,102 INFO  [stdout] (default task-144) Found KeyTab /etc/krb5.keytab for keycloak/...@... 
21:29:26,102 INFO  [stdout] (default task-144) Found KeyTab /etc/krb5.keytab for keycloak/...@... 
21:29:26,103 INFO  [stdout] (default task-144) Found KeyTab /etc/krb5.keytab for keycloak/...@...
21:29:26,104 INFO  [stdout] (default task-144) Found KeyTab /etc/krb5.keytab for keycloak/...@...
21:29:26,104 INFO  [stdout] (default task-144) Entered Krb5Context.acceptSecContext with state=STATE_NEW                                                                                                                                      
21:29:26,104 INFO  [stdout] (default task-144) Looking for keys for: keycloak/...@...
21:29:26,104 INFO  [stdout] (default task-144) Found unsupported keytype (3) for keycloak/...@...
21:29:26,104 INFO  [stdout] (default task-144) Found unsupported keytype (8) for keycloak/...@...
21:29:26,104 INFO  [stdout] (default task-144) Found unsupported keytype (25) for keycloak/...@...
21:29:26,104 INFO  [stdout] (default task-144) Found unsupported keytype (26) for keycloak/...@...
21:29:26,104 INFO  [stdout] (default task-144) Added key: 23version: 2                                                                                                                                                                        
21:29:26,104 INFO  [stdout] (default task-144) Added key: 16version: 2                                                                                                                                                                        
21:29:26,104 INFO  [stdout] (default task-144) Added key: 17version: 2                                                                                                                                                                        
21:29:26,104 INFO  [stdout] (default task-144) Added key: 18version: 2                                                                                                                                                                        
21:29:26,104 INFO  [stdout] (default task-144) >>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType                                                                                                                            
21:29:26,105 INFO  [stdout] (default task-144) Using builtin default etypes for permitted_enctypes                                                                                                                                            
21:29:26,105 INFO  [stdout] (default task-144) default etypes for permitted_enctypes: 18 17 20 19 16 23.                                                                                                                                      
21:29:26,105 INFO  [stdout] (default task-144) >>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType                                                                                                                            
21:29:26,105 INFO  [stdout] (default task-144) MemoryCache: add ... to centos@...|keycloak/...@...
21:29:26,106 INFO  [stdout] (default task-144) >>> KrbApReq: authenticate succeed.                                                                                                                                                            
21:29:26,106 INFO  [stdout] (default task-144) Krb5Context setting peerSeqNumber to: 693469989                                                                                                                                                
21:29:26,106 INFO  [stdout] (default task-144) Krb5Context setting mySeqNumber to: 693469989                                                                                                                                                  
21:29:26,107 WARN  [org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator] (default task-144) SPNEGO login failed: java.lang.NullPointerException                                                                                         
        at org.keycloak.keycloak-common@12.0.4//org.keycloak.common.util.Base64.encodeBytes(Base64.java:720)                                                                                                                                  
        at org.keycloak.keycloak-kerberos-federation@12.0.4//org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator.establishContext(SPNEGOAuthenticator.java:170)                                                                         
        at org.keycloak.keycloak-kerberos-federation@12.0.4//org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator$AcceptSecContext.run(SPNEGOAuthenticator.java:132)                                                                     
        at org.keycloak.keycloak-kerberos-federation@12.0.4//org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator$AcceptSecContext.run(SPNEGOAuthenticator.java:122)                                                                     
        at java.base/java.security.AccessController.doPrivileged(Native Method)                                                                                                                                                               
        at java.base/javax.security.auth.Subject.doAs(Subject.java:423)                                                                                                                                                                       
        at org.keycloak.keycloak-kerberos-federation@12.0.4//org.keycloak.federation.kerberos.impl.SPNEGOAuthenticator.authenticate(SPNEGOAuthenticator.java:68)                                                                              
        at org.keycloak.keycloak-kerberos-federation@12.0.4//org.keycloak.federation.kerberos.KerberosFederationProvider.authenticate(KerberosFederationProvider.java:193)                                                                    
        at org.keycloak.keycloak-services@12.0.4//org.keycloak.credential.UserCredentialStoreManager.lambda$authenticate$13(UserCredentialStoreManager.java:284)                                                                              
<snip>
21:29:26,117 WARN  [org.keycloak.events] (default task-144) type=LOGIN_ERROR, realmId=..., clientId=..., userId=null, ipAddress=..., error=invalid_user_credentials, auth_method=openid-connect, auth_type=code, response_
type=code, redirect_uri=https://.../, code_id=..., response_mode=query, authSessionParentId=..., authSessionTabId=...
```

A successful login (using 0.12) results in the following Keycloak logs:
```
21:35:15,278 INFO  [stdout] (default task-143) Found KeyTab /etc/krb5.keytab for keycloak/...@... 
21:35:15,278 INFO  [stdout] (default task-143) Found KeyTab /etc/krb5.keytab for keycloak/...@... 
21:35:15,279 INFO  [stdout] (default task-143) Found KeyTab /etc/krb5.keytab for keycloak/...@... 
21:35:15,279 INFO  [stdout] (default task-143) Found KeyTab /etc/krb5.keytab for keycloak/...@...
21:35:15,279 INFO  [stdout] (default task-143) Entered Krb5Context.acceptSecContext with state=STATE_NEW
21:35:15,280 INFO  [stdout] (default task-143) Looking for keys for: keycloak/...@...
21:35:15,280 INFO  [stdout] (default task-143) Found unsupported keytype (3) for keycloak/...@... 
21:35:15,280 INFO  [stdout] (default task-143) Found unsupported keytype (8) for keycloak/...@... 
21:35:15,280 INFO  [stdout] (default task-143) Found unsupported keytype (25) for keycloak/...@...
21:35:15,280 INFO  [stdout] (default task-143) Found unsupported keytype (26) for keycloak/...@...
21:35:15,280 INFO  [stdout] (default task-143) Added key: 23version: 2
21:35:15,280 INFO  [stdout] (default task-143) Added key: 16version: 2
21:35:15,280 INFO  [stdout] (default task-143) Added key: 17version: 2
21:35:15,280 INFO  [stdout] (default task-143) Added key: 18version: 2
21:35:15,280 INFO  [stdout] (default task-143) >>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
21:35:15,280 INFO  [stdout] (default task-143) Using builtin default etypes for permitted_enctypes
21:35:15,280 INFO  [stdout] (default task-143) default etypes for permitted_enctypes: 18 17 20 19 16 23.
21:35:15,280 INFO  [stdout] (default task-143) >>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
21:35:15,281 INFO  [stdout] (default task-143) MemoryCache: add .../centos@... to centos@...|keycloak/...@...
21:35:15,281 INFO  [stdout] (default task-143) >>> KrbApReq: authenticate succeed.
21:35:15,281 INFO  [stdout] (default task-143) Krb5Context setting peerSeqNumber to: 848991744
21:35:15,281 INFO  [stdout] (default task-143) >>> EType: sun.security.krb5.internal.crypto.Aes256CtsHmacSha1EType
21:35:15,282 INFO  [stdout] (default task-143) Krb5Context setting mySeqNumber to: 820126497
21:35:15,282 INFO  [stdout] (default task-143) >>> Constrained deleg from GSSCaller{UNKNOWN}
```

It appears Keycloak expects something in the request it can base64-encode which is given when using 0.12 but isn't when using 0.13/`spnego`.

I'm not sure how to further troubleshoot/debug this, appreciate any suggestions.

**Comment by NicolasT** [comment]
Thanks for getting back! It's a weird issue indeed.

Client is Linux (CentOS 7). I tried with the latest Keycloak (15.0.2), same issue (previous was 12.0.4).

I'll test with more debug logging later. I've also been working on a `docker-compose` based setup which should make it easy (or easier, at least) to share the setup (can't share the 'real' app though, but I bet it's trivial to write a small reproducer script, will look into that). The app works fine when using 0.12, when upgrading to 0.13 (`pip install` in venv), without changing any of the running services, it breaks.

The 302 is expected (OpenID Authorization flow redirect to the original app). The 200 in the faulty setting I believe is rendered because Kerberos/SPNEGO authn failed (at least, threw an exception), after which Keycloak falls back to a form-based login.

**Comment by NicolasT** [comment]
I dumped a 'good' (0.12) `Negotiate` value using the `spnego` module as well as a 'bad' (0.13) one. There's a diff (next to `cipher` and `RawData` values):

```
$ diff -u good.txt bad.txt 
--- good.txt    2021-11-08 21:19:02.560528860 +0000
+++ bad.txt     2021-11-08 21:18:54.123310528 +0000
@@ -8,10 +8,8 @@
                 "pvno": 5,
                 "msg-type": "AP-REQ (14)",
                 "ap-options": {
-                    "raw": 32,
-                    "flags": [
-                        "mutual-required (32)"
-                    ]
+                    "raw": 0,
+                    "flags": []
                 },
                 "ticket": {
                     "tkt-vno": 5,
```

**Comment by jborean93** [comment]
Thanks for the details, do you set `mutual_authentication=DISABLED` when creating `HTTPKerberosAuth`? There was a slight change when setting the context options https://github.com/requests/requests-kerberos/commit/f211fe8e96d43a5fe86d02c846dda671553623e1#diff-5fd1d9057d55d4d66fe4ed7fcc85be0c5968f87b4e1fb9aa48ff24f969e02c39L199-R200

Before both the `GSS_C_SEQUENCE_FLAG` and `GSS_C_MUTUAL_FLAG` was set even when the caller didn't request mutual auth at all whereas now `GSS_C_MUTUAL_FLAG` is skipped if the client has explicitly disabled it. If so you could try and ` mutual_authentication=OPTIONAL` or `mutual_authentication=REQUIRED`. I could somehow reason that the service is expecting a token to send back to the client for mutual auth and it isn't equipped to handle the case where the mutual flag isn't set and thus wouldn't have a token to send back (the value is null).

**Comment by NicolasT** [comment]
You're right. I tried with "optional" mutual auth, using v0.13, and now Keycloak happily handles the request and my test-suite succeeds. Indeed, when dumping the header value, the `mutual-required` flag is set, as it was in 0.12, even when setting mutual authn to `disabled`.

So, I guess Keycloak and 'for real' disabled mutual authn is a no-go. *Required* mutual authn also fails with Keycloak, so in the end I guess there's only one working setting.

Closing now, since this appears not to be an issue in this lib or its dependencies. Thanks for the help!

**Comment by jborean93** [comment]
> Required mutual authn also fails with Keycloak, so in the end I guess there's only one working setting.

That's interesting, usually this means the server you are talking to isn't who the client thinks it is. If you have an error handy it would be interesting to see what it is but If you are happy with having mutual auth as optional then that's fine by me. Using HTTPS provides the mutual auth on the TLS layer anyway.

I mostly modeled the change on what `requests-gssapi` does https://github.com/pythongssapi/requests-gssapi/blob/0402d14235783716635a1ea08bd0b1c63dc69272/requests_gssapi/gssapi_.py#L132-L136 and while this is technically a breaking change in your scenario I would think it wrong for the client to request mutual auth if it's not going to validate the response at all. So in your case `OPTIONAL` seems to be the way to go and happy that is resolves your issue.

Thanks for confirming the problem, hopefully it helps anyone else in the future that may come across it as well.
