### ISSUE TITLE
Cannot install requests_kerberos with pip

### ISSUE THREAD

**Issue by we29758143** [requests/requests-kerberos#175]
I'm trying to install requests_kerberos, however got the following errors, did anyone has the same issue?

```
Collecting gssapi>=1.5.0
  Using cached gssapi-1.7.3.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      In distributed package, building from C files...
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-haxqg1_z/gssapi_3d2630e8257e4cef94209a43cf7fc008/setup.py", line 225, in <module>
          GSSAPI_LIB = ctypes.CDLL(os.path.join(main_path, main_lib))
        File "/data2/nlp_development/anaconda3/envs/singutxt-2/lib/python3.7/ctypes/__init__.py", line 364, in __init__
          self._handle = _dlopen(self._name, mode)
      OSError: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Machine config:
```
Operating System: Red Hat Enterprise Linux 8.5 (Ootpa)
CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
Kernel: Linux 4.18.0-348.el8.x86_64
Architecture: x86-64
```

Not sure where did I do wrong, I googled is there any similar solution and tried implementing it. Still got the error, can anyone help?
It looks like an issue on OS side?

**Comment by paolosime** [comment]
Had the same issue and it's been solved by installing the right package:
`sudo apt-get install libkrb5-dev`

**Comment by KristianKjerstad** [comment]
> Had the same issue and it's been solved by installing the right package: `sudo apt-get install libkrb5-dev`

@mkomitee Would be nice to add this to the README / docs
