### ISSUE TITLE
Pip install failure: popenargs not defined

### ISSUE THREAD

**Issue by wontonst** [requests/requests-kerberos#66]
I tried both

```pip install requests-kerberos```

and downloading master.zip and pip installing that way.

Both ways result in stderr ```Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1gTsvg/pykerberos/```

It also spits out a ton of stuff to stdout

```
Collecting https://pypi.python.org/packages/source/r/requests-kerberos/requests-kerberos-0.8.0.tar.gz
  Using cached requests-kerberos-0.8.0.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from requests-kerberos==0.8.0)
Collecting pykerberos<2.0.0,>=1.1.8 (from requests-kerberos==0.8.0)
  Using cached pykerberos-1.1.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1gTsvg/pykerberos/setup.py", line 57, in <module>
        krb5_ver = check_krb5_version()
      File "/tmp/pip-build-1gTsvg/pykerberos/setup.py", line 50, in check_krb5_version
        if len(krb5_vers) == 4:
    TypeError: object of type 'NoneType' has no len()
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1gTsvg/pykerberos/setup.py", line 57, in <module>
        krb5_ver = check_krb5_version()
      File "/tmp/pip-build-1gTsvg/pykerberos/setup.py", line 49, in check_krb5_version
        krb5_vers = check_krb5_config("--version")
      File "/tmp/pip-build-1gTsvg/pykerberos/setup.py", line 43, in check_krb5_config
        return check_krb5_config(*options, command_name="krb5-config.mit")
      .........lots of repeat........
              return check_krb5_config(*options, command_name="krb5-config.mit")
      File "/tmp/pip-build-1gTsvg/pykerberos/setup.py", line 43, in check_krb5_config
        return check_krb5_config(*options, command_name="krb5-config.mit")
      File "/tmp/pip-build-1gTsvg/pykerberos/setup.py", line 37, in check_krb5_config
        cmd = popenargs[0]
    NameError: global name 'popenargs' is not defined

    ----------------------------------------

```

**Comment by Lukasa** [comment]
That bug is in pykerberos. You'll need to take it up with that project I'm afraid.
