### ISSUE TITLE
Request using mutual auth returns 200 but raises MutualAuthenticationError

### ISSUE THREAD

**Issue by tuukkamustonen** [requests/requests-kerberos#94]
With `0.11.0` (`requests == 2.14.1`, `pykerberos == 1.1.14`):

```python
requests.get('https://SERVER', verify=False, auth=HTTPKerberosAuth())
```

Raises:

```python
Traceback (most recent call last):
  File "<ipython-input-39-a3f889e087c4>", line 1, in <module>
    requests.get('https://SERVER', verify=False, auth=HTTPKerberosAuth(mutual_authentication=1))
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/requests/sessions.py", line 646, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/requests_kerberos/kerberos_.py", line 287, in handle_response
    return self.handle_response(_r, num_401s=num_401s, **kwargs)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/requests_kerberos/kerberos_.py", line 294, in handle_response
    _r = self.handle_other(response)
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/requests_kerberos/kerberos_.py", line 217, in handle_other
    "{0}".format(response))
MutualAuthenticationError: Unable to authenticate <Response [200]>
```

That looks weird - the server returned `200` but it is reported as a failure?

I stepped some code, and response from the server is indeed correct (containing expected response body etc.).

Enabling logging gives:

```python
ERROR:requests_kerberos.kerberos_:authenticate_server(): authGSSClientStep() failed:
Traceback (most recent call last):
  File "/home/musttu/Code/virtualenvs/cosmos/lib/python3.4/site-packages/requests_kerberos/kerberos_.py", line 258, in authenticate_server
    result = kerberos.authGSSClientStep(self.context[host],
kerberos.GSSError: (('Invalid token was supplied', 589824), ('Success', 100001))
ERROR:requests_kerberos.kerberos_:handle_other(): Mutual authentication failed
```

Setting `force_preemptive=True` makes no difference.

Setting `mutual_authentication=DISABLE` makes the call succeed... but shouldn't it work also with enabled?

The target server is Jenkins, if that matters.

**Comment by sigmavirus24** [comment]
Based on the logging you provided, it look as though the kerberos library that we're using is what actually causes this error.

**Comment by sigmavirus24** [comment]
I don't have a good idea of what that means. I do _suspect_ (based on your analysis alone) that the kerberos module is being very precise and that the Jenkins server is probably returning something that's acceptable to more flexible validators.

**Comment by JensTimmerman** [comment]
This seems to be in line with what the documentation claims?
```
By default, HTTPSPNEGOAuth will require mutual authentication from the server, and if a server emits a non-error response which cannot be authenticated, a requests_gssapi.errors.MutualAuthenticationError will be raised. 
```

**Comment by JensTimmerman** [comment]
you can set `mutual_authentication=OPTIONAL` but I'm not sure this is what you want?

**Comment by suzuito** [comment]
Are you reusing invalid `session` object of Request library?
Same issue was occured on my application.
I changed that `session` object was initialized after request was failed, and fixed it.

**Comment by jborean93** [comment]
Closing as per https://github.com/requests/requests-kerberos/issues/94#issuecomment-300453353. The response from the server is a 200 indicating it accepting the client token but the mutual auth error comes from the client processing the token from the server indicating it's not who the client thinks it is.
