### ISSUE TITLE
issue with pywin32 is breaking requests-kerberos on Python 3.6.1

### ISSUE THREAD

**Issue by akapocsi** [requests/requests-kerberos#99]
Here is an example of the issue:

```
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> from requests_kerberos import HTTPKerberosAuth
>>> r = requests.post('http://redacted-url.com/example', auth=HTTPKerberosAuth())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\envs\test\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Anaconda3\envs\test\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Anaconda3\envs\test\lib\site-packages\requests\sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda3\envs\test\lib\site-packages\requests\sessions.py", line 646, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "C:\Anaconda3\envs\test\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "C:\Anaconda3\envs\test\lib\site-packages\requests_kerberos\kerberos_.py", line 268, in handle_response
    _r = self.handle_401(response, **kwargs)
  File "C:\Anaconda3\envs\test\lib\site-packages\requests_kerberos\kerberos_.py", line 176, in handle_401
    _r = self.authenticate_user(response, **kwargs)
  File "C:\Anaconda3\envs\test\lib\site-packages\requests_kerberos\kerberos_.py", line 151, in authenticate_user
    auth_header = self.generate_request_header(response)
  File "C:\Anaconda3\envs\test\lib\site-packages\requests_kerberos\kerberos_.py", line 112, in generate_request_header
    "{0}@{1}".format(self.service, host), gssflags=gssflags)
  File "C:\Anaconda3\envs\test\lib\site-packages\kerberos_sspi.py", line 186, in authGSSClientInit
    ctx={"csa":sspi.ClientAuth("Kerberos", scflags=gssflags, targetspn=spn),
  File "C:\Anaconda3\envs\test\lib\site-packages\win32\lib\sspi.py", line 111, in __init__
    None, auth_info)
ValueError: year 30828 is out of range
```

This issue has also been raised on [sourcefourge](https://sourceforge.net/p/pywin32/bugs/748/), but I thought it should be raised here as well since pywin32 is a dependency.  If this is not appropriate or necessary, please don't hesitate to close this.

**Comment by behackett** [comment]
Recent versions of requests-kerberos use WinKerberos instead of kerberos-sspi. WinKerberos ignores the expiration timestamp (just like PyKerberos), avoiding this issue. Upgrading requests-kerberos should solve your problem.

**Comment by akapocsi** [comment]
Looks like Anaconda is shipping v0.8.0 with their latest Python (3.6.1) distribution.

Updating requests-kerberos to v0.11.0 via pip solved my issue.

Thanks!

**Comment by scholtes** [comment]
Interesting that the year out of range happens to be 30828.  

Windows uses [64 bit signed integers to represent time in number of 100-nanonsecond chunks since the year 1601](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724290), which results in the latest possible representable time being 100*(2^63-1) Nanoseconds since epoch, which is the year 30828.

**Comment by behackett** [comment]
The problem is Python's datetime type [rejects values for year beyond 9999](https://docs.python.org/2/library/datetime.html#datetime.MAXYEAR).
